// <auto-generated />
namespace MyConcert.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createconcerttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createconcerttable));
        
        string IMigrationMetadata.Id
        {
            get { return "201802211423543_create-concert-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
